config/routes.rb
Rails.application.routes.draw do
  resources :runs
  mount Crono::Web, at: '/crono'
  
#  get 'trades/add_trades'
  get 'trades/index'
  get 'trades/show_trades'
  get 'trades/candlesticks'
  get 'trades/create_cash'
  get 'trades/order_book'
  get 'trades/update_cash'
  
  
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.haml
.container-fluid
  .row
    .col-md-1
      %h5= link_to "Home",         root_path
    .col-md-2
      %h5= link_to "Add Trades",   trades_index_path
    .col-md-2
      %h5= link_to "Create Cash",  trades_create_cash_path
    .col-md-2
      %h5= link_to "Update Cash",  trades_update_cash_path
    .col-md-2
      %h5= link_to "Candlesticks", trades_candlesticks_path
    .col-md-2
      %h5= link_to "Order Book",   trades_order_book_path
    .col-md-1
      %h5= link_to "Runs",         runs_path
%hr

app/views/shared/_tickers.html.haml
%h3.text-primary= 'Tickers'
- if @tickers.present?
  .container-fluid
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th= 'Pair'
          %th= 'Max. Price'
          %th= 'Min. Price'
          %th= 'Avg. Price'
          %th= 'Volume'
          %th= 'Vol. Currency'
          %th= 'Last Trade Price'
          %th= 'Buy'
          %th= 'Sell'
          %th= 'Updated'
      %tbody
        - @tickers.each do |ticker|
          %tr
            %td= ticker.first.first
            %td= ticker.first.last['high']
            %td= ticker.first.last['low']
            %td= ticker.first.last['avg']
            %td= ticker.first.last['vol']
            %td= ticker.first.last['vol_cur']
            %td= ticker.first.last['last']
            %td= ticker.first.last['buy']
            %td= ticker.first.last['sell']
            %td= date_from_timestamp ticker.first.last['updated']