config/routes.rb
Rails.application.routes.draw do
  resources :runs
  mount Crono::Web, at: '/crono'
  
#  get 'trades/add_trades'
  get 'trades/index'
  get 'trades/show_trades'
  get 'trades/candlesticks'
  get 'trades/create_cash'
  get 'trades/order_book'
  get 'trades/update_cash'
  
  
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/run.rb
################################################################################
# Model:  Run
#
# Purpose:
#
# Run attributes:
#   coin       - Foreign key
#   kind       - strategy type:             enum { ask (sell) (0) | bid (buy) (1) }
#   depo       - amount to be used:         decimal
#   last       - last closed trade price:   decimal
#   start      - price step to first order %: float
#   overlay    - price overlay (first - last orders) %:   float
#   martingale -  %:                        float
#   orders     - number of orders:          integer
#   profit     - in %:                      float
#   scale      - order prices range ascale: enum { linear (0) | logarithmic (1) }
#   stop_loss  - stop loss:                 decimal
#   status     - Run status:                enum { opened (0) | closed (1) | aborted (2) }
#   
#  16.01.2018 ZT
################################################################################
class Run < ApplicationRecord
  belongs_to :coin
  
  enum kind:   %w(ask bid)
  enum scale:  %w(linear logarithmic)
  enum status: %w(opened closed aborted)
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  include DataPro
  
  before_action :set_run, only: [:show, :edit, :update, :destroy]

  # GET /runs
  # GET /runs.json
  def index
    @runs = Run.all
    
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
  end

  # GET /runs/new
  def new
    @run = Run.new
    
    # Update Tickers
    @pair_names = []
    @tickers    = []
    Coin.all.each do |coin|
      pair_name = coin.pair.name
      @pair_names << pair_name
      @tickers << get_ticker(pair_name)
    end
    

    @run.coin = Coin.first
    @run.last = @tickers.first.first.last['last']
    if @run.kind == 'ask'
      @run.stop_loss = @run.last * (1. - @run.overlay * 2 / 100.0)
    else
      @run.stop_loss = @run.last * (1. + @run.overlay * 2 / 100.0)
    end
    puts @run.inspect
    gon.pair_names = @pair_names
    gon.tickers    = @tickers#.to_json
    puts gon.tickers
  end

  def edit
  end

  def create
    @run = Run.new(run_params)
    puts "ZT! #{@run}"

    respond_to do |format|
      if @run.save!
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render :show, status: :created, location: @run }
      else
        format.html { render :new }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update!(run_params)
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { render :show, status: :ok, location: @run }
      else
        format.html { render :edit }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url, notice: 'Run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:pair_id, :kind, :depo, :last, :start, :overlay, :martingale, :orders, :profit, :scale, :stop_loss, :status)
    end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/_form.html.haml
= include_gon(:init => true)
%div= render 'shared/tickers'
.row
  .col-md-2
    = simple_form_for(@run) do |f|
      = f.error_notification

      .form-inputs
        = f.association :coin, autofocus: true, input_html: {onchange: "changeLastPrice()"}

        = f.input :kind
        = f.input :depo
        = f.input :last
        = f.input :start
        = f.input :overlay
        = f.input :martingale
        = f.input :orders
        = f.input :profit
        = f.input :scale
        = f.input :stop_loss
        = f.input :status

      .form-actions
        = f.button :submit

app/views/runs/edit.html.haml
%h1 Editing run

= render 'form'

= link_to 'Show', @run
\|
= link_to 'Back', runs_path

app/views/runs/index.html.haml
%h1 Listing runs
.container-fluid
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Pair
        %th Kind
        %th Depo
        %th Last
        %th Start
        %th Overlay
        %th Martingale
        %th Orders
        %th Profit
        %th Scale
        %th Stop loss
        %th Status
        %th
        %th
        %th

    %tbody
      - @runs.each do |run|
        %tr
          %td= run.coin
          %td= run.kind
          %td= run.depo
          %td= run.last
          %td= run.start
          %td= run.overlay
          %td= run.martingale
          %td= run.orders
          %td= run.profit
          %td= run.scale
          %td= run.stop_loss
          %td= run.status
          %td= link_to 'Show', run
          %td= link_to 'Edit', edit_run_path(run)
          %td= link_to 'Destroy', run, method: :delete, data: { confirm: 'Are you sure?' }

  %br

  = link_to 'New Run', new_run_path

app/views/runs/new.html.haml
%h1 New run

= render 'form'

= link_to 'Back', runs_path

app/views/runs/show.html.haml
%p#notice= notice

%p
  %b Coin:
  = @run.coin
%p
  %b Kind:
  = @run.kind
%p
  %b Depo:
  = @run.depo
%p
  %b Last:
  = @run.last
%p
  %b Start:
  = @run.start
%p
  %b Overlay:
  = @run.overlay
%p
  %b Martingale:
  = @run.martingale
%p
  %b Orders:
  = @run.orders
%p
  %b Profit:
  = @run.profit
%p
  %b Scale:
  = @run.scale
%p
  %b Stop loss:
  = @run.stop_loss
%p
  %b Status:
  = @run.status

= link_to 'Edit', edit_run_path(@run)
\|
= link_to 'Back', runs_path